#Number Guessing Game
import random
print("Welcome to the number guessing game!!\nInstructions:\n1.Enter a number between 0 and 10 when asked.\n2.The computer will generate a number in random.\n3. If your number is equal to the number generated by the computer you will be awarded a point else point goes to the computer.\n4. The winner is decided by the number of rounds each of you win")
rounds=int(input("How many rounds do you want?"))
comp_score=0
player_score=0
for i in range(1,rounds+1):
    comp_num=random.randint(0,10)
    player_num=int(input("Guess a number between 0 and 10:"))
    print("Round:",i)
    print("Computer Generated number:",comp_num)
    print("Number entered by player:",player_num)
    if(comp_num==player_num):
        player_score+=1
        print("Hurray! You guessed the number")
    else:
        comp_score+=1
        print("Oops! You entered the wrong number")
print("Results:")
print("\t\t\tPlayer's score\t\t\tComputer's score")
print("\t\t\t\t",player_score,"\t\t\t\t",comp_score)
if player_score>comp_score:
    print("Congratulations!!! You won")
elif player_score<comp_score:
    print("OOPs!! Good try. Better luck next time")
else:
    print("You are so close! It's a draw.")





